console.log('apple');
console.log('bananas');
console.log('testing feat');
console.log('testing fix');
console.log('testing docs');
console.log('testing style');
console.log('testing refactor');
console.log('testing perf');
console.log('testing test');
console.log('testing ci');
console.log('testing build');
console.log('testing chore');

console.log('this is a fix');
console.log('this is a feature');
console.log('this is a ci change');
console.log('this is another feature');
console.log('this is another fix');
console.log('this is a breaking change');
console.log('this is a feature');
